#index:
#    path: /
#    controller: App\Controller\DefaultController::index


check_path:
  path: /login
  methods: [POST]

upload_image:
  path: /api/upload
  controller: App\Controller\UploadFileController
  methods: POST
